describe('slice.my', () => {
  test('empty', () => {
    expect(''.slice()).toEqual('');
    expect(''.slice(0)).toEqual('');
    expect(''.slice(-1)).toEqual('');
    expect(''.slice(1)).toEqual('');
    expect(''.slice(1.1)).toEqual('');
    expect(''.slice(2.2)).toEqual('');
    expect(''.slice(2.6)).toEqual('');
    expect(''.slice(2.9)).toEqual('');
    expect(''.slice(NaN)).toEqual('');
    expect(''.slice(Infinity)).toEqual('');
    expect(''.slice(-Infinity)).toEqual('');
    expect(''.slice(1, 0)).toEqual('');
    expect(''.slice(1, 1)).toEqual('');
    expect(''.slice(1, -1)).toEqual('');
    expect(''.slice(1, 1.1)).toEqual('');
    expect(''.slice(1, 2.2)).toEqual('');
    expect(''.slice(1, 2.6)).toEqual('');
    expect(''.slice(1, 2.9)).toEqual('');
    expect(''.slice(1, NaN)).toEqual('');
    expect(''.slice(1, Infinity)).toEqual('');
    expect(''.slice(1, -Infinity)).toEqual('');
  });

  test('valid', () => {
    expect('example'.slice()).toEqual('example');
    expect('example'.slice(0)).toEqual('example');
    expect('example'.slice(-1)).toEqual('e');
    expect('example'.slice(-1.1)).toEqual('e');
    expect('example'.slice(-2)).toEqual('le');
    expect('example'.slice(-2.2)).toEqual('le');
    expect('example'.slice(-2.6)).toEqual('le');
    expect('example'.slice(-2.9)).toEqual('le');
    expect('example'.slice(1)).toEqual('xample');
    expect('example'.slice(1.1)).toEqual('xample');
    expect('example'.slice(2.2)).toEqual('ample');
    expect('example'.slice(2.6)).toEqual('ample');
    expect('example'.slice(2.9)).toEqual('ample');
    expect('example'.slice(NaN)).toEqual('example');
    expect('example'.slice(Infinity)).toEqual('');
    expect('example'.slice(-Infinity)).toEqual('example');
    expect('example'.slice(1, 0)).toEqual('');
    expect('example'.slice(1, 1)).toEqual('');
    expect('example'.slice(1, -1)).toEqual('xampl');
    expect('example'.slice(1, 1.1)).toEqual('');
    expect('example'.slice(1, 2.2)).toEqual('x');
    expect('example'.slice(1, 2.6)).toEqual('x');
    expect('example'.slice(1, 2.9)).toEqual('x');
    expect('example'.slice(1, -1.1)).toEqual('xampl');
    expect('example'.slice(1, -2.2)).toEqual('xamp');
    expect('example'.slice(1, -2.6)).toEqual('xamp');
    expect('example'.slice(1, -2.9)).toEqual('xamp');
    expect('example'.slice(1, NaN)).toEqual('');
    expect('example'.slice(1, Infinity)).toEqual('xample');
    expect('example'.slice(1, -Infinity)).toEqual('');
    expect('example'.slice(NaN, Infinity)).toEqual('example');
  });
});
